version: "3.5"

services:
  app:
    container_name: site-formation-ensa-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
